### ISSUE TITLE
Wrong behave when translator loaded on background

### ISSUE THREAD

**Issue by Stepan-H** [Factral/GoogleTranslateDarkTheme#1]
When I let browser open translate.google.* on background (In Firefox by middle button mouse), translator dark mode does not apply coreectly. Some part of page is white and buttons for open list of languages look like white to dark "rainbow" (Sorry, don't know properly term.). When I press F5 for reload than page load correctly. I added simple reload script at the end of your script, I but it did not help, because problem is connected with loading on background... This problem I am not able to solve, I am not so good in programming...

**Comment by Factral** [comment]
Can you send a screenshot?
it only happens with firefox have you tried it with any other browser?
I haven't had that error and I don't know how to replicate it.

**Comment by Stepan-H** [comment]
I am using Mozilla Firefox (actually 92.0 64bit). I haven't tested other browsers. 
I enclose two screenshots. On the first load, which shows an "error", and the second frame after I redraw the page using F5.

![Výstřižek](https://user-images.githubusercontent.com/31160576/132813127-656f8f43-7a73-4d6a-b69b-1c06f696167d.PNG)
![Výstřižek_b](https://user-images.githubusercontent.com/31160576/132813420-6ab5c01b-e882-4ec4-af06-1a187e2ebbf7.PNG)

**Comment by Factral** [comment]
you can update the style to the new version.
test if the problem persists, if it does, make sure you have updated the stylus extension or you have a bad configuration.
otherwise, record the screen when the problem happens, personally I don't use firefox so I don't know what to do.

**Comment by Stepan-H** [comment]
How to install it to userscript manager Tampermonkey?

**Comment by Factral** [comment]
you can install it with [greasyfork](https://greasyfork.org/en/scripts/422285-google-translate-dark/code), just click on "install this script" and you're done.
that should fix your problem

**Comment by Factral** [comment]
oh lol, I just got the same problem trying it with tampermonkey(never happened to me with stylus), I never had it before, if I have time I'll see how to solve it.

**Comment by Stepan-H** [comment]
Userscript from GrasyFork version 1.0.2 solved language selectors
, but lover half of page remains white and also circle buttons History, Saved and Contibute.
When I click on History, It show list of History with full white border.
After F5 refreshed page seems good, but after showing History, there are white header and footer in list of History.
First picture is again before F5 refresh, second picture after F5 and than click History.

![Výstřižek_c](https://user-images.githubusercontent.com/31160576/132907113-5f58bc5c-932a-4c76-ae08-4095ef2692c5.PNG)
![Výstřižek_d](https://user-images.githubusercontent.com/31160576/132907420-7cf9ec5d-6cd8-4690-bb95-cb9cf7f80504.PNG)

**Comment by Factral** [comment]
**problem fixed**, the problem arose because tampermonkey loads the cutom style before all the styles of the page are applied so some styles lost their priority and were not applied to the DOM.
upgrade to the new version
