### ISSUE TITLE
Burger menu text

### ISSUE THREAD

**Issue by Korb** [Factral/GoogleTranslateDarkTheme#10]
![2024-11-11_23-29-01](https://github.com/user-attachments/assets/b6b05ddc-99b9-4e5d-8037-7c0528051af7)

Mozilla Firefox 133.0b6 (64-bit)
Stylus 1.5.51 (August 22, 2024)
Google Translate Dark 1.3.2

**Comment by Factral** [comment]
hi @Korb , thanks for continuing to use the extension after so long. 
The commit [1a463ad](https://github.com/Factral/GoogleTranslateDarkTheme/commit/1a463ad3cae265d4f0645fb1c4a72553a25b651c) fixes that problem, thanks for reporting it.
