### ISSUE TITLE
White in black

### ISSUE THREAD

**Issue by Stepan-H** [Factral/GoogleTranslateDarkTheme#2]
Google again chagend something and there are started showing white title/header...

![Výstřižek_c](https://user-images.githubusercontent.com/31160576/136206914-85324ba2-f41d-42cb-a300-81f3d2f3a334.PNG)

Please, make update for usersrcript too (no only userstyle) on greasyfork.org ...

Thank you very much.

**Comment by Factral** [comment]
Fixed, you can upgrade with greasyfork to version [1.2](https://greasyfork.org/en/scripts/422285-google-translate-dark).sometimes google adds styles and breaks the dark theme, thanks for the report

**Comment by Factral** [comment]
btw, when you install with greasyfork, it automatically converts the userstyle to userscript like this
![image](https://user-images.githubusercontent.com/74687828/136227784-f08eac8c-6248-4cdb-be70-2a4b0ee322c4.png)
