### ISSUE TITLE
Background color not working in translated text window

### ISSUE THREAD

**Issue by Korb** [Factral/GoogleTranslateDarkTheme#3]
Style is off:
![Screen Shot 2022-10-13 at 10 38 16](https://user-images.githubusercontent.com/3509797/195532771-e6a126f3-1bab-41eb-b5df-11062faf4cd3.png)

Style is on:
![Screen Shot 2022-10-13 at 10 38 00](https://user-images.githubusercontent.com/3509797/195532794-d476e901-9699-49aa-8ba7-e8e889f5b849.png)

Mozilla Firefox 105.0.3 (64-bit), Microsoft Windows 10.0.19044.2130

**Comment by Factral** [comment]
Now it should work fine, I'd appreciate it if you could star the repo :)

**Comment by Korb** [comment]
> Now it should work fine

Nope.
![Google Translate Dark 1 2 background bug](https://user-images.githubusercontent.com/3509797/195775488-b7904067-6394-4842-9f7b-168ae73dac1c.gif)

**Comment by Factral** [comment]
check now please
