### ISSUE TITLE
[enhancement] Custom back translation text color setting

### ISSUE THREAD

**Issue by Korb** [Factral/GoogleTranslateDarkTheme#5]
![2022-10-16_19-22-58](https://user-images.githubusercontent.com/3509797/196046758-174f031d-4be2-4da8-9303-3bd4421c2898.png)
The interface of such functionality from the user's side in another custom style looks like this:
![2022-10-16_19-09-37](https://user-images.githubusercontent.com/3509797/196046768-22f01dbf-e530-413e-986b-6b6f78b90f31.png)
The fact is that reverse translation is convenient for indirect control of the correctness of the translation. Usually, I make it quite contrasting. With the current value, you have to strain to distinguish between low-contrast text:

> Foreground: #5F6368
> Background: #213342
> The contrast ratio is: 2.1:1
> 1.4.3 Contrast (Minimum) (AA). Fail for large and regular text
> 1.4.6 Contrast (Enhanced) (AAA). Fail for large and regular text
> 1.4.11 Non-text Contrast (AA). Fail for UI components and graphical objects

**Comment by Factral** [comment]
i agree with you, the text does not read very well

>  The interface of such functionality from the user's side in another custom style looks like this:

what would be the purpose of that interface? i mean this style has a lot of colors and backgrounds in a lot of places, that can make the interface a mess

>  With the current value, you have to strain to distinguish between low-contrast text:

about the color of the text, I propose to give it the color #acacac, which is used in other parts of the style, using this color the contrast will be "5.7:1 ok" , here is a preview
![image](https://user-images.githubusercontent.com/74687828/196048336-5a1e5594-18ee-458f-8b28-33e9b5f943be.png)


what do u think?

**Comment by Korb** [comment]
This is good, but not perfect:

> Foreground: `#9D9FA1`
> Background: `#213342`
> Contrast ratio: 4.891:1
> 1.4.3 Contrast (Minimum) (AA)
> ✔ Pass for regular text
> 1.4.6 Contrast (Enhanced) (AAA)
> ❌ Fail for regular text

Note: [Writing UserCSS / user-customizable variables](https://github.com/openstyles/stylus/wiki/Writing-UserCSS#var).
