### ISSUE TITLE
Issue with Google translate

### ISSUE THREAD

**Issue by Bamboozul** [Factral/GoogleTranslateDarkTheme#6]
![Screenshot 2022-11-07 193914](https://user-images.githubusercontent.com/101983929/200377966-696af8a8-b3f8-4a2e-ac0f-fbe858c1148d.png)

[Link](https://translate.google.as/?hl=ar)

**Comment by Factral** [comment]
fixed 
![image](https://user-images.githubusercontent.com/74687828/201555613-3d99f249-7f2d-4ad8-8d44-ca2811999926.png)
