### ISSUE TITLE
Add GoogleTranslateDarkTheme to userstyles.org and userstyles.world

### ISSUE THREAD

**Issue by Korb** [Factral/GoogleTranslateDarkTheme#9]
I believe that this dark style for Google Translate is better than others posted on these sites, and it is worthy of high ratings from grateful users.

**Comment by Factral** [comment]
Thanks for your interest and suggestion!
I've added the dark style for Google Translate in userstyles.word. Check it out here: https://userstyles.world/style/1036/google-translate-dark-theme

Also, i think userstyles.org might be down at the moment.
